"""Safety helpers for local model artifact persistence."""

from __future__ import annotations

import pickle
from pathlib import Path
from typing import TypeVar

import joblib

T = TypeVar("T")


def _resolve_trusted_artifact_path(
    path: Path,
    *,
    trusted_root: Path,
    allowed_suffixes: set[str],
) -> Path:
    root = trusted_root.resolve()
    resolved = path.resolve()
    if resolved.suffix.lower() not in allowed_suffixes:
        raise ValueError(f"unsupported model artifact suffix: {resolved.suffix}")
    if not resolved.is_relative_to(root):
        raise ValueError(f"model artifact is outside trusted directory: {resolved}")
    return resolved


def load_trusted_pickle(path: Path, *, trusted_root: Path, expected_type: type[T]) -> T:
    """Load a pickle artifact only from a trusted local model directory.

    Pickle is unsafe for untrusted data. This helper narrows usage to artifacts
    generated by this application under the configured data directory and
    verifies the expected object type after loading.
    """
    resolved = _resolve_trusted_artifact_path(
        path,
        trusted_root=trusted_root,
        allowed_suffixes={".pkl", ".pickle"},
    )
    with resolved.open("rb") as file_obj:
        artifact = pickle.load(file_obj)  # noqa: S301 - guarded trusted local model artifact
    if not isinstance(artifact, expected_type):
        raise TypeError(
            f"unexpected model artifact type: {type(artifact).__name__}; "
            f"expected {expected_type.__name__}"
        )
    return artifact


def dump_trusted_pickle(value: object, path: Path, *, trusted_root: Path) -> None:
    """Persist a pickle artifact under the trusted local model directory."""
    resolved = _resolve_trusted_artifact_path(
        path,
        trusted_root=trusted_root,
        allowed_suffixes={".pkl", ".pickle"},
    )
    resolved.parent.mkdir(parents=True, exist_ok=True)
    with resolved.open("wb") as file_obj:
        pickle.dump(value, file_obj)


def load_trusted_joblib(path: Path, *, trusted_root: Path, expected_type: type[T]) -> T:
    """Load a joblib artifact only from a trusted local model directory."""
    resolved = _resolve_trusted_artifact_path(
        path,
        trusted_root=trusted_root,
        allowed_suffixes={".joblib"},
    )
    artifact = joblib.load(resolved)
    if not isinstance(artifact, expected_type):
        raise TypeError(
            f"unexpected model artifact type: {type(artifact).__name__}; "
            f"expected {expected_type.__name__}"
        )
    return artifact


def dump_trusted_joblib(value: object, path: Path, *, trusted_root: Path) -> None:
    """Persist a joblib artifact under the trusted local model directory."""
    resolved = _resolve_trusted_artifact_path(
        path,
        trusted_root=trusted_root,
        allowed_suffixes={".joblib"},
    )
    resolved.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(value, resolved)
