"""Canonical single-model contract for the Phase 3 runtime."""

from __future__ import annotations

from core.model_topology import ModelTopology, qwen27_candidate_topology

PHASE3_TARGET_MODEL_ID = "qwen3.8-27b"
PHASE3_TARGET_MODEL_REPO_ID = "Qwen/Qwen3.8-27B"
PHASE3_TARGET_MODEL_ENDPOINT = "http://127.0.0.1:18000/v1"
PHASE3_TARGET_MODEL_PORT = 8000
PHASE3_TARGET_SERVICE_NAME = "bb-phase3-llm-target.service"
PHASE3_TARGET_MODEL_PATH = "/data/BB/models/qwen3.8-27b"
PHASE3_QUANT_API_ID = "phase3_quant_api"

PHASE3_PLATFORM_ENDPOINTS = {
    PHASE3_TARGET_MODEL_ID: PHASE3_TARGET_MODEL_ENDPOINT,
    PHASE3_QUANT_API_ID: "http://127.0.0.1:18001",
}
PHASE3_MODEL_SERVER_SERVICES = (
    (PHASE3_TARGET_SERVICE_NAME, PHASE3_TARGET_MODEL_ID, PHASE3_TARGET_MODEL_PORT),
)
PHASE3_REQUIRED_LLM_MODEL_IDS = frozenset({PHASE3_TARGET_MODEL_ID})
PHASE3_APPROVED_RUNTIME_MODEL_PATHS = (PHASE3_TARGET_MODEL_PATH,)

PHASE3_TARGET_MODEL_TOPOLOGY: ModelTopology = qwen27_candidate_topology(
    repo_id=PHASE3_TARGET_MODEL_REPO_ID,
    path=PHASE3_TARGET_MODEL_PATH,
)
