"""Runtime entry-filter helpers.

Entry filters are advisory signals produced by strategy learning. They are used
for ranking, sizing, leverage confidence, and user-facing explanations. They are
not hard entry gates; hard blocks must remain limited to safety/exchange checks.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

from config.settings import settings
from services.trading_params import DEFAULT_TRADING_PARAMS

_RUNTIME_PARAMS = DEFAULT_TRADING_PARAMS.strategy_learning


@dataclass(frozen=True, slots=True)
class RuntimeEntryFilters:
    """Dynamic entry filter thresholds generated by strategy learning."""

    min_entry_volume_ratio: float
    min_entry_adx: float
    source: str = "strategy_learning_runtime"
    is_hard_entry_gate: bool = False
    reason: str = ""

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["policy"] = "dynamic_advisory_not_entry_gate"
        return payload


def _safe_float(value: Any, default: float) -> float:
    try:
        if value is None:
            return default
        result = float(value)
        return result if result == result else default
    except (TypeError, ValueError):
        return default


def _clamp(value: float, lower: float, upper: float) -> float:
    return max(lower, min(value, upper))


def _safe_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def default_entry_filters(*, reason: str = "settings_bootstrap") -> RuntimeEntryFilters:
    """Return a bounded default used only before runtime learning is available."""

    return RuntimeEntryFilters(
        min_entry_volume_ratio=_clamp(
            _safe_float(
                settings.min_entry_volume_ratio, _RUNTIME_PARAMS.entry_volume_ratio_default
            ),
            _RUNTIME_PARAMS.entry_volume_ratio_min,
            _RUNTIME_PARAMS.entry_volume_ratio_max,
        ),
        min_entry_adx=_clamp(
            _safe_float(settings.min_entry_adx, _RUNTIME_PARAMS.entry_adx_default),
            _RUNTIME_PARAMS.entry_adx_min,
            _RUNTIME_PARAMS.entry_adx_max,
        ),
        source="settings_bootstrap",
        is_hard_entry_gate=False,
        reason=reason,
    )


def entry_filters_from_context(context: dict[str, Any] | None) -> RuntimeEntryFilters:
    """Read dynamic filters from strategy context with bounded fallback."""

    if not isinstance(context, dict):
        return default_entry_filters(reason="runtime_context_missing")

    candidates = [
        _safe_dict(context.get("entry_filters")),
        _safe_dict(_safe_dict(context.get("strategy_learning")).get("entry_filters")),
        _safe_dict(_safe_dict(context.get("strategy_learning_context")).get("entry_filters")),
        _safe_dict(_safe_dict(context.get("strategy_mode")).get("entry_filters")),
    ]
    for candidate in candidates:
        if not candidate:
            continue
        return RuntimeEntryFilters(
            min_entry_volume_ratio=_clamp(
                _safe_float(
                    candidate.get("min_entry_volume_ratio"),
                    settings.min_entry_volume_ratio,
                ),
                _RUNTIME_PARAMS.entry_volume_ratio_min,
                _RUNTIME_PARAMS.entry_volume_ratio_max,
            ),
            min_entry_adx=_clamp(
                _safe_float(candidate.get("min_entry_adx"), settings.min_entry_adx),
                _RUNTIME_PARAMS.entry_adx_min,
                _RUNTIME_PARAMS.entry_adx_max,
            ),
            source=str(candidate.get("source") or "strategy_learning_runtime"),
            is_hard_entry_gate=False,
            reason=str(candidate.get("reason") or "runtime_entry_filters"),
        )
    return default_entry_filters(reason="runtime_entry_filters_unavailable")


def entry_filters_from_decision(decision: Any) -> RuntimeEntryFilters:
    """Read dynamic filters attached to a decision raw response."""

    raw = getattr(decision, "raw_response", None)
    if not isinstance(raw, dict):
        return default_entry_filters(reason="decision_runtime_context_missing")
    return entry_filters_from_context(raw)
